# Set prefix to Ctrl+s instead of Ctrl+B
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# hjkl pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable mouse support
set -g mouse on

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# True color support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Tokyo Night colors
set -g status-style bg='#1a1b26',fg='#c0caf5'
set -g status-left '#[fg=#7aa2f7,bold] ❐ #S '
set -g status-right '#[fg=#7dcfff] %H:%M #[fg=#9ece6a]%d-%m-%Y '
set -g window-status-current-style fg='#7aa2f7',bold
set -g pane-border-style fg='#565f89'
set -g pane-active-border-style fg='#7aa2f7'

# Split panes with | and -
bind | split-window -h
bind - split-window -v
